feat: update gc script

diff --git a/dots/scripts/gc b/dots/scripts/gc
--- a/dots/scripts/gc
+++ b/dots/scripts/gc
@@ -16,6 +16,22 @@ help() {
     echo "  project, p     Set the default project"
 }
 
+help_login() {
+  if [ -n "$1" ]; then
+        echo "Error: $1"
+        echo ""
+  fi
+
+  echo "Google Cloud Login Utils"
+  echo ""
+  echo "Usage: gc login <connect | c>"
+  echo ""
+  echo "Commands:"
+  echo "  help, h        Show this help"
+  echo "  connect, c     Connect to Google Cloud"
+  echo "  get, g         Get the current email"
+}
+
 if [ $# -eq 0 ]; then
     help
     exit 1
@@ -26,8 +42,22 @@ case "$1" in
         help
         ;;
     login | l)
-        gcloud auth login --no-browser
-        gcloud auth application-default login --no-browser
+        case "$2" in
+          help | h)
+            help_login
+            ;;
+          connect | c)
+            gcloud auth login --no-browser
+            gcloud auth application-default login --no-browser
+          ;;  
+          get | g)
+            gcloud auth list
+          ;;
+          *)
+            help_login "Unknown command"
+            exit 1
+            ;;
+        esac
         ;;
     project | p)
         if [ -z "$2" ]; then
